services:
    php:
      build:
        context: .
        dockerfile: config/php/dockerfile
      volumes:
        - ./src:/var/www/html:delegated
        - ./config/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        - ./config/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      container_name: php_kids_math_testig
      networks:
        - kids_math_testig_network

    server:
      build:
        context: .
        dockerfile: config/nginx/dockerfile
      ports:
        - 8080:80
      volumes:
        - ./src:/var/www/html
      depends_on:
        - php
        - mysql
      container_name: server_kids_math_testig
      networks:
        - kids_math_testig_network

    mysql:
      image: mariadb:11.4.2
      restart: unless-stopped
      tty: true
      env_file:
        - config/mysql/.env
      volumes:
          - /opt/mysql_data:/var/lib/mysql
      ports:
          - 3306:3306
      container_name: mysql_kids_math_testig
      networks:
        - kids_math_testig_network

    artisan:
      build:
        context: .
        dockerfile: config/php/dockerfile
      volumes:
        - ./src:/var/www/html
      entrypoint: ["php", "/var/www/html/artisan"]
      depends_on:
        - mysql
      networks:
        - kids_math_testig_network

    scheduler:
      build:
        context: ./
        dockerfile: config/php/dockerfile
      volumes:
        - ./src:/var/www/html
      working_dir: /var/www/html
      entrypoint: [ "php", "artisan", "schedule:work" ]
      container_name: scheduler_kids_math_testig
      networks:
        - kids_math_testig_network

networks:
  kids_math_testig_network:
    driver: bridge

volumes:
    mysqldata: {}